############### Docker Hub ##################  
trigger:
- main
- main-production

pool:
  name: 'Windows pool DEV' 
  # vmImage: ubuntu-latest

steps:
  # - task: ShellScript@2
  #   displayName: Install DockerInstaller@0
  #   inputs:
  #     scriptPath: 'docker-compose-install.sh'
  - task: Docker@2
    inputs:
      command: 'login'
      containerRegistry: 'nsconnectiontaskschedulinglaravellumen'
      displayName: 'Docker Login'

  # - script: |
  #     docker pull danielesco/apistoextractfrompmc:v1
  #   displayName: 'Docker Pull v1'

  - task: Docker@2
    inputs:
      repository: 'danielesco/task_scheduling_laravel_lumen'
      command: 'build'
      Dockerfile: 'Dockerfile'  # Ensure the correct Dockerfile path
      tags: 'v1'
      displayName: 'Docker Build'

  - task: Docker@2
    inputs:
      repository: 'danielesco/task_scheduling_laravel_lumen'
      command: 'push'
      tags: 'v1'
      displayName: 'Docker Push'


  - task: AzureCLI@2
    inputs:
      azureSubscription: 'appServicesConnection'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az webapp config container set --name 'CMPDEV-LAP-APC003' --resource-group 'CMPRG1DEV-RG-APICASES001' --docker-custom-image-name 'danielesco/task_scheduling_laravel_lumen:v1' --docker-registry-server-url 'https://index.docker.io/v1/'
        az webapp restart --name 'CMPDEV-LAP-APC003' --resource-group 'CMPRG1DEV-RG-APICASES001'
    displayName: 'Azure Web App Container Deploy'


  




  
  





  

  